# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arcdist <- function(x, y) {
    .Call(`_ShapeKRRC_Arcdist`, x, y)
}

ARCG <- function(x, y, Sig) {
    .Call(`_ShapeKRRC_ARCG`, x, y, Sig)
}

#' Kernel Ridge Regreggion Classifier with Intrinsic Kernel
#'
#' @param x Training Array for building subspaces
#' @param xtest Test set (Array)
#' @param y Test label
#' @param Sig the regularization parameter for kernel
#' @param lambda the regularization parameter for Ridge Reg
#' @return Est_Mat distance matrix
#' @export
KRRC_ARC <- function(x, xtest, y, Sig, lambda) {
    .Call(`_ShapeKRRC_KRRC_ARC`, x, xtest, y, Sig, lambda)
}

VWdist <- function(x, y) {
    .Call(`_ShapeKRRC_VWdist`, x, y)
}

EVWG <- function(x, y, Sig) {
    .Call(`_ShapeKRRC_EVWG`, x, y, Sig)
}

#' Kernel Ridge Regreggion Classifier with Veronese Whitney Gaussian
#'
#' @param x Training Array for building subspaces
#' @param xtest Test set (Array)
#' @param y Test label
#' @param Sig the regularization parameter for kernel
#' @param lambda the regularization parameter for Ridge Reg
#' @return Est_Mat distance matrix
#' @export
KRRC_VWG <- function(x, xtest, y, Sig, lambda) {
    .Call(`_ShapeKRRC_KRRC_VWG`, x, xtest, y, Sig, lambda)
}

